config/routes.rb
Pluto::Application.routes.draw do
  match "tasks", :controller => "tasks", :action => "day"

  get "top/index"

  match "/auth/:provider/callback" => "sessions#callback"
  match "/auth/failure" => "sessions#failure"
  match "/logout" => "sessions#destroy", :as => :logout

  root :to => 'top#index'

  match ':controller(/:action(/:id))(.:format)'
  match ':controller(/:action)', :to => 'users#show'
end

app/models/task.rb
class Task < ActiveRecord::Base
  scope :comp, where( :complete_flag => true )
  scope :incomp, where( :complete_flag => false )
end

app/models/user.rb
# coding: utf-8
class User < ActiveRecord::Base

  #---------------------------#
  # self.create_with_omniauth #
  #---------------------------#
  def self.create_with_omniauth( auth )
    user = User.new
    user[:provider] = auth["provider"]
    user[:uid] = auth["uid"]
    
    unless auth["info"].blank?
      user[:name] = auth["info"]["name"]
      user[:screen_name] = auth["info"]["nickname"]
      user[:image] = auth["info"]["image"]
    end
    
    user.save
    
    return user
  end

end

app/controllers/application_controller.rb
# coding: utf-8
class ApplicationController < ActionController::Base
  
  protect_from_forgery
  
  # 未ログインリダイレクト
  before_filter :authorize

  # httpsリダイレクト
  before_filter :ssl_redirect unless Rails.env.development?
  
  # セッション有効期限延長
  before_filter :reset_session_expires

  private

  #-----------#
  # authorize #
  #-----------#
  # ログイン認証
  def authorize
    # セッション、トップコントローラ以外で
    if params[:controller] != "sessions" and params[:controller] != "top"
      # 未ログインであればルートヘリダイレクト
      if session[:user_id].blank?
        redirect_to :root and return
      end
    end
    
    # トップコントローラで
    if params[:controller] == "top"
      # ログイン済みであればtaskへリダイレクト
      unless session[:user_id].blank?
        redirect_to :controller => "tasks" and return
      end
    end
  end

  #--------------#
  # ssl_redirect #
  #--------------#
  def ssl_redirect
    unless request.env["HTTP_X_FORWARDED_PROTO"].to_s == "https"
      # httpsへリダイレクト
      request.env["HTTP_X_FORWARDED_PROTO"] = "https"
      redirect_to request.url and return
    end
  end
  
  #-----------------------#
  # reset_session_expires #
  #-----------------------#
  # セッション期限延長
  def reset_session_expires
    request.session_options[:expire_after] = 2.weeks
  end

  #--------------#
  # current_user #
  #--------------#
  def current_user
    @current_user ||= User.where( :id => session[:user_id] ).first
  end
  
  helper_method :current_user

end

app/controllers/sessions_controller.rb
# coding: utf-8
class SessionsController < ApplicationController

  #----------#
  # callback #
  #----------#
  def callback
    auth = request.env["omniauth.auth"]
    user = User.where( :provider => auth["provider"], :uid => auth["uid"] ).first || User.create_with_omniauth( auth )
    session[:user_id] = user.id
    redirect_to :root, :notice => "login"
  end

  #---------#
  # destroy #
  #---------#
  def destroy
    session[:user_id] = nil
    redirect_to :root, :notice => "Logged out"
  end

  #---------#
  # failure #
  #---------#
  def failure
    render :text => "<span style='color: red;'>Auth Failure</span>"
  end

end

app/controllers/tasks_controller.rb
# coding: utf-8
class TasksController < ApplicationController

=begin
  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = Task.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(params[:task])

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render json: @task, status: :created, location: @task }
      else
        format.html { render action: "new" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end
=end

  #-----#
  # day #
  #-----#
  def day
    @task = Task.new
    @tasks = Task.incomp.where( :user_id => session[:user_id], :span => "day" ).limit( LIST_LIMIT ).order( 'priority DESC, added_at DESC' )
  end
  
  #------#
  # week #
  #------#
  def week
    @task = Task.new
    @tasks = Task.incomp.where( :user_id => session[:user_id], :span => "week" ).limit( LIST_LIMIT ).order( 'priority DESC, added_at DESC' )
  end
  
  #-------#
  # month #
  #-------#
  def month
    @task = Task.new
    @tasks = Task.incomp.where( :user_id => session[:user_id], :span => "month" ).limit( LIST_LIMIT ).order( 'priority DESC, added_at DESC' )
  end
  
  #------#
  # comp #
  #------#
  def comp
    @tasks = Task.comp.where( :user_id => session[:user_id] ).limit( LIST_LIMIT ).order( 'completed_at DESC' )
  end

  #--------#
  # create #
  #--------#
  def create
    @task = Task.new( params[:task] )
    @task.user_id = session[:user_id]
    @task.added_at = Time.now

    unless @task.save
      alert = "タスクの作成に失敗しました。"
    end

    redirect_to :action => @task.span, :alert => alert
  end

  #------#
  # done #
  #------#
  def done
    task = Task.where( :user_id => session[:user_id], :id => params[:id] ).first
    result = task.update_attributes( :complete_flag => true, :completed_at => Time.now )
    
    unless result
      alert = "タスクの完了に失敗しました。"
    end
    
    redirect_to :action => task.span, :alert => alert
  end

  #----------#
  # priority #
  #----------#
  def priority
    task = Task.where( :user_id => session[:user_id], :id => params[:id] ).first
    result = task.update_attributes( :priority => params[:priority] )
    
    unless result
      alert = "更新が失敗しました。"
    end
    
    redirect_to :action => task.span, :alert => alert
  end

  #---------#
  # destroy #
  #---------#
  def destroy
    task = Task.where( :user_id => session[:user_id], :id => params[:id] ).first
    result = task.destroy
    
    unless result
      alert = "タスクの作成に失敗しました。"
    end
    
    redirect_to :action => task.span, :alert => alert
  end

end

app/controllers/top_controller.rb
# coding: utf-8
class TopController < ApplicationController

  #-------#
  # index #
  #-------#
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
  case level
  when :notice then 'info'
  when :error then 'error'
  when :alert then 'warning'
  end
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Pluto</title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le styles -->
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>

    <!-- Le fav and touch icons -->
    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
          <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="i-bar"></span>
            <span class="i-bar"></span>
            <span class="i-bar"></span>
          </a>
          <a class="brand" href="/">Pluto</a>
          <%# FIXME: ↓のクラス指定があると(Safari,Chrome)以外でリストメニューが表示されない 2012/02/11 %>
          <div class="container nav-collapse">
          <ul class="nav">
              <% if current_user %>
                <%# ログイン済み %>
                <li><%= link_to "Day" , :controller => 'tasks', :action => 'day' %></li>
                <li><%= link_to "Week" , :controller => 'tasks', :action => 'week' %></li>
                <li><%= link_to "Month" , :controller => 'tasks', :action => 'month' %></li>
                <li><%= link_to "Comp" , :controller => 'tasks', :action => 'comp' %></li>
                <li><%= link_to "Logout" , logout_path %></li>
              <% else %>
                <%# 未ログイン %>
                <li><%= link_to "Login", "/auth/#{if Rails.env.production? then 'twitter' else 'developer' end}" %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="content">
          <div class="row">
            <div class="span9">
            <% [:notice, :error, :alert].each do |level| %>
            <% unless flash[level].blank? %>
             <div data-alert="alert" class="alert alert-<%= flash_class(level) %> fade in">
                <a class="close" data-dismiss="alert" href="#">&times;</a>
                <%= content_tag :p, flash[level] %>
              </div>
              <% end %>
            <% end %>
            <%= yield %>
            </div>
          </div>
        </div>

      <footer>
        <p>&copy; shu_0115 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/tasks/______form.html.erb
<div class="clearfix">
   <%= f.label :title, t("activerecord.attributes.task.title", :default => "Title"), :class => :label %>
  <div class="input">
    <%= f.text_field :title, :class => 'text_field' %>
  </div>
</div>

<div class="clearfix">
   <%= f.label :span, t("activerecord.attributes.task.span", :default => "Span"), :class => :label %>
  <div class="input">
    <%= f.text_field :span, :class => 'text_field' %>
  </div>
</div>

<div class="clearfix">
   <%= f.label :priority, t("activerecord.attributes.task.priority", :default => "Priority"), :class => :label %>
  <div class="input">
    <%= f.number_field :priority, :class => 'number_field' %>
  </div>
</div>

<div class="clearfix">
   <%= f.label :added_at, t("activerecord.attributes.task.added_at", :default => "Added at"), :class => :label %>
  <div class="input">
    <%= f.datetime_select :added_at, :class => 'datetime_select' %>
  </div>
</div>

<div class="clearfix">
   <%= f.label :completed_at, t("activerecord.attributes.task.completed_at", :default => "Completed at"), :class => :label %>
  <div class="input">
    <%= f.datetime_select :completed_at, :class => 'datetime_select' %>
  </div>
</div>
<div class="form-actions">
  <button class="btn primary" type="submit">Save</button> or
	<%= link_to "Cancel", tasks_path %>
</div>

app/views/tasks/_____edit.html.erb
<%= form_for @task, :url => task_path(@task), :html => { :class => "edit_task", :id => "edit_task" } do |f| -%>
  <input name="_method" type="hidden" value="put" />
  <%= render :partial => "form", :locals => {:f => f} %>
<% end -%>

app/views/tasks/_____index.html.erb
<h1>Tasks</h1>
<table class="table table-striped">
 <thead>
  <tr>
    <th>ID</th>
        <th>
      <%= t("activerecord.attributes.task.title", :default => t("activerecord.labels.title", :default => "Title")) %>
    </th>
        <th>Created at</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @tasks.each do |task| -%>
   <tr>
    <td><%= task.id %></td>
        <td><%= link_to task.title, task_path(task) %>
    </td>
        <td><%= task.created_at %></td>
    <td>
      <%= link_to "Show", task_path(task) %>
      <%= link_to "Edit", edit_task_path(task) %>
      <%= link_to "Destroy", task_path(task), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
    </td>
    </tr>
    <% end -%>
   </tbody>
</table>

<%= link_to "New", new_task_path, :class => 'btn btn-primary' %>

app/views/tasks/_____new.html.erb
<%= form_for @task, :url => tasks_path, :html => { :class => :form } do |f| -%>
  <%= render :partial => "form", :locals => {:f => f} %>
<% end -%>

app/views/tasks/_____show.html.erb
<label class="label"><%= t("activerecord.attributes.task.title", :default => t("activerecord.labels.title", :default => "Title")) %>:</label>
<p><%= @task.title %></p>

<label class="label"><%= t("activerecord.attributes.task.span", :default => t("activerecord.labels.span", :default => "Span")) %>:</label>
<p><%= @task.span %></p>

<label class="label"><%= t("activerecord.attributes.task.priority", :default => t("activerecord.labels.priority", :default => "Priority")) %>:</label>
<p><%= @task.priority %></p>

<label class="label"><%= t("activerecord.attributes.task.added_at", :default => t("activerecord.labels.added_at", :default => "Added at")) %>:</label>
<p><%= @task.added_at %></p>

<label class="label"><%= t("activerecord.attributes.task.completed_at", :default => t("activerecord.labels.completed_at", :default => "Completed at")) %>:</label>
<p><%= @task.completed_at %></p>

<div class="form-actions">
<%= link_to "Back", tasks_path, :class => 'btn'  %>
<%= link_to "Edit", edit_task_path(@task), :class => 'btn' %>
<%= link_to "Delete", task_path(@task), :method => "delete", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}", :class => 'btn' %>
</div>

app/views/tasks/comp.html.erb
<h2>Comp</h2>

<table class="table table-striped">
 <thead>
  <tr>
    <th>No.</th>
    <th>ラベル</th>
    <th>タスク</th>
    <th>完了日</th>
    <th>追加日</th>
  </tr>
  </thead>
  
  <tbody>
  <% @tasks.each_with_index{ |task, index| -%>
    <tr>
      <td><%= index + 1 %></td>
      <td><%= task.span %></td>
      <td><%= task.title %></td>
      <td><%= task.completed_at.strftime("%Y年%m月%d日") unless task.completed_at.blank? %></td>
      <td><%= task.added_at.strftime("%Y年%m月%d日") unless task.added_at.blank? %></td>
    </tr>
  <% } -%>
  </tbody>
</table>

app/views/tasks/day.html.erb
<h2>Day</h2>

<%= form_for @task, :url => { :action => 'create' }, :html => { :class => :form } do |f| -%>
  <%= f.hidden_field :span, { :value => 'day' } %>

  <div class="clearfix">
     <%= f.label :title, t("activerecord.attributes.task.title", :default => "タスク"), :class => :label %>
    <div class="input">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  
  <div class="form-actions">
    <%# FIXME: :disable_withで二度押し防止出来ない 2012/02/11 %>
    <%= f.submit "Add", :disable_with => "Add", :class => "btn primary" %><br />
  </div>
<% end -%>

<table class="table table-striped">
 <thead>
  <tr>
    <th></th>
    <th>No.</th>
    <th>タスク</th>
    <th>追加日</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
    
  <% @tasks.each_with_index{ |task, index| -%>
   <tr>
    <td>
      <% if task.priority > 0 %>
        <%= link_to "★", { :action => 'priority', :id => task.id, :priority => 0 } %>
      <% else %>
        <%= link_to "☆", { :action => 'priority', :id => task.id, :priority => 1 } %>
      <% end %>
    </td>
    <td><%= index + 1 %></td>
    <td><%= task.title %></td>
    <td><%= task.added_at.strftime("%Y年%m月%d日") unless task.added_at.blank? %></td>
    <td>
      <%= link_to "Done", { :action => 'done', :id => task.id }, :onClick=>"return confirm('完了します。よろしいですか？');" %>
    </td>
    <td>
      <%#= link_to "Show", task_path(task) %>
      <%#= link_to "Edit", edit_task_path(task) %>
      <%# FIXME: confirmオプションだとポップアップが二重に表示される(TwitterBootstrap周りが原因？) %>
      <%#= link_to "Delete", { :action => 'destroy', :id => task.id }, :confirm => "#{t("web-app-theme.confirm", :default => "本当に削除してもよろしいですか？")}" %>
      <%= link_to "Delete", { :action => 'destroy', :id => task.id }, :onClick=>"return confirm('本当に削除してもよろしいですか？');" %>
    </td>
    </tr>
    <% } -%>
   </tbody>
</table>

app/views/tasks/month.html.erb
<h2>Month</h2>

<%= form_for @task, :url => { :action => 'create' }, :html => { :class => :form } do |f| -%>
  <%= f.hidden_field :span, { :value => 'month' } %>

  <div class="clearfix">
     <%= f.label :title, t("activerecord.attributes.task.title", :default => "タスク"), :class => :label %>
    <div class="input">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  
  <div class="form-actions">
    <button class="btn primary" type="submit">Add</button>
  </div>
<% end -%>

<table class="table table-striped">
 <thead>
  <tr>
    <th></th>
    <th>No.</th>
    <th>タスク</th>
    <th>追加日</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
    
  <% @tasks.each_with_index{ |task, index| -%>
   <tr>
    <td>
      <% if task.priority > 0 %>
        <%= link_to "★", { :action => 'priority', :id => task.id, :priority => 0 } %>
      <% else %>
        <%= link_to "☆", { :action => 'priority', :id => task.id, :priority => 1 } %>
      <% end %>
    </td>
    <td><%= index + 1 %></td>
    <td><%= task.title %></td>
    <td><%= task.added_at.strftime("%Y年%m月%d日") unless task.added_at.blank? %></td>
    <td>
      <%= link_to "Done", { :action => 'done', :id => task.id }, :onClick=>"return confirm('完了します。よろしいですか？');" %>
    </td>
    <td>
      <%#= link_to "Show", task_path(task) %>
      <%#= link_to "Edit", edit_task_path(task) %>
      <%#= link_to "Destroy", task_path(task), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      <%= link_to "Delete", { :action => 'destroy', :id => task.id }, :onClick=>"return confirm('本当に削除してもよろしいですか？');" %>
    </td>
    </tr>
    <% } -%>
   </tbody>
</table>

app/views/tasks/week.html.erb
<h2>Week</h2>

<%= form_for @task, :url => { :action => 'create' }, :html => { :class => :form } do |f| -%>
  <%= f.hidden_field :span, { :value => 'week' } %>

  <div class="clearfix">
     <%= f.label :title, t("activerecord.attributes.task.title", :default => "タスク"), :class => :label %>
    <div class="input">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  
  <div class="form-actions">
    <button class="btn primary" type="submit">Add</button>
  </div>
<% end -%>

<table class="table table-striped">
 <thead>
  <tr>
    <th></th>
    <th>No.</th>
    <th>タスク</th>
    <th>追加日</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
    
  <% @tasks.each_with_index{ |task, index| -%>
   <tr>
    <td>
      <% if task.priority > 0 %>
        <%= link_to "★", { :action => 'priority', :id => task.id, :priority => 0 } %>
      <% else %>
        <%= link_to "☆", { :action => 'priority', :id => task.id, :priority => 1 } %>
      <% end %>
    </td>
    <td><%= index + 1 %></td>
    <td><%= task.title %></td>
    <td><%= task.added_at.strftime("%Y年%m月%d日") unless task.added_at.blank? %></td>
    <td>
      <%= link_to "Done", { :action => 'done', :id => task.id }, :onClick=>"return confirm('完了します。よろしいですか？');" %>
    </td>
    <td>
      <%#= link_to "Show", task_path(task) %>
      <%#= link_to "Edit", edit_task_path(task) %>
      <%#= link_to "Destroy", task_path(task), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      <%= link_to "Delete", { :action => 'destroy', :id => task.id }, :onClick=>"return confirm('本当に削除してもよろしいですか？');" %>
    </td>
    </tr>
    <% } -%>
   </tbody>
</table>

app/views/top/index.html.erb
<h1>Top#index</h1>
<p>Find me in app/views/top/index.html.erb</p>